openapi: 3.0.0
info:
  title: Tài liệu API
  description: "[Giới thiệu dự án](https://agilts.atlassian.net/wiki)"
  version: 1.0.0
servers:
  - url: http://localhost
    description: Máy chủ địa phương
  - url: https://backend.agilts.com
    description: Máy chủ công khai
paths:
  /sanctum/csrf-cookie:
    $ref: "./paths/sanctum/csrf-cookie.yaml"
  /api/register:
    $ref: "./paths/api/register.yaml"
  /api/login:
    $ref: "./paths/api/login.yaml"
  /api/logout:
    $ref: "./paths/api/logout.yaml"
  /auth/redirect/{driver_name}:
    $ref: "./paths/auth/redirect/{driver_name}.yaml"
  /api/two-factor-challenge:
    $ref: "./paths/api/two-factor-challenge.yaml"
  /api/user/two-factor-authentication:
    $ref: "./paths/api/user/two-factor-authentication.yaml"
  /api/user/two-factor-qr-code:
    $ref: "./paths/api/user/two-factor-qr-code.yaml"
  /api/user/confirmed-two-factor-authentication:
    $ref: "./paths/api/user/confirmed-two-factor-authentication.yaml"
  /api/user/two-factor-recovery-codes:
    $ref: "./paths/api/user/two-factor-recovery-codes.yaml"
  /api/user/two-factor-secret-key:
    $ref: "./paths/api/user/two-factor-secret-key.yaml"
  /api/email/verification-notification:
    $ref: "./paths/api/email/verification-notification.yaml"
  /api/user/confirm-password:
    $ref: "./paths/api/user/confirm-password.yaml"
  /api/user/confirmed-password-status:
    $ref: "./paths/api/user/confirmed-password-status.yaml"
  /api/forgot-password:
    $ref: "./paths/api/forgot-password.yaml"
  /api/reset-password:
    $ref: "./paths/api/reset-password.yaml"
  /api/user/password:
    $ref: "./paths/api/user/password.yaml"
  /api/user/profile-information:
    $ref: "./paths/api/user/profile-information.yaml"
  /api/address/province:
    $ref: "./paths/api/address/province.yaml"
  /api/address/district/{province_id}:
    $ref: "./paths/api/address/district/{province_id}.yaml"
  /api/address/ward/{district_id}:
    $ref: "./paths/api/address/ward/{district_id}.yaml"
  /api/address:
    $ref: "./paths/api/address.yaml"
  /api/address/{address_id}:
    $ref: "./paths/api/address/{address_id}.yaml"
  /api/identification:
    $ref: "./paths/api/identification.yaml"
  /api/identification/{identification_id}:
    $ref: "./paths/api/identification/{identification_id}.yaml"
  /api/social:
    $ref: "./paths/api/social.yaml"
  /api/social/{social_id}:
    $ref: "./paths/api/social/{social_id}.yaml"
  /api/product/{product_type}/filter:
    $ref: "./paths/api/product/{product_type}/filter.yaml"
  /api/product/{product_type}:
    $ref: "./paths/api/product/{product_type}.yaml"
  /api/product/{product_type}/{product_id}:
    $ref: "./paths/api/product/{product_type}/{product_id}.yaml"
  /api/branch:
    $ref: "./paths/api/branch.yaml"
  /api/branch/{branch_id}:
    $ref: "./paths/api/branch/{branch_id}.yaml"
  /api/wishlist:
    $ref: "./paths/api/wishlist.yaml"
  /api/wishlist/{wishlist_id}:
    $ref: "./paths/api/wishlist/{wishlist_id}.yaml"
  /api/cart:
    $ref: "./paths/api/cart.yaml"
  /api/cart/{cart_id}:
    $ref: "./paths/api/cart/{cart_id}.yaml"
  /api/review:
    $ref: "./paths/api/review.yaml"
  /api/review/{review_id}:
    $ref: "./paths/api/review/{review_id}.yaml"
