openapi: 3.0.0
info:
  title: Tài liệu API
  description: "[Giới thiệu dự án](https://agilts.atlassian.net/wiki)"
  version: 1.0.0
servers:
  - url: http://localhost
    description: Máy chủ địa phương
  - url: https://backend.agilts.com
    description: Máy chủ công khai
paths:
  /sanctum/csrf-cookie:
    $ref: "./paths/sanctum/csrf-cookie.yaml"
  /api/register:
    $ref: "./paths/api/register.yaml"
